name: Build and run on push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
      working-directory: bsearch
    - name: make run
      run: make run
      working-directory: bsearch
